### ISSUE TITLE
About Training Time

### ISSUE THREAD

**Issue by LinzhouLi** [yufan1012/MonoGaussianAvatar#6]
Hi, thanks for your great work!
        I have a question about how mamy epochs do you used for training a head avatar in total? I follow the default setting in the training script (600 epochs) and found training a video with 3600 frames is about 3 days using a single RTX3090. This is far more time cost than that in the paper (9 hours). I want to know how to match the training speed in the paper. Appreciate for your rely!

**Comment by yufan1012** [comment]
about 120 epoch

**Comment by yufan1012** [comment]
about 120 epochs

**Comment by LinzhouLi** [comment]
Thanks.
